### ISSUE TITLE
which mate error

### ISSUE THREAD

**Issue by acarabott** [rfwatson/supercollider-tmbundle#2]
Latest change by sbl to recognise Mate directory has broken the TextMate.sc. On startup now get

ERROR: Message 'unixCmdGetStdOut' not understood.
RECEIVER:
Instance of String {    (05FC3830, gc=01, fmt=07, flg=11, set=01)
  indexed slots [10]
      0 : w
      1 : h
      2 : i
      3 : c
      4 : h
      5 :  
      6 : m
      7 : a
      8 : t
      9 : e
}
ARGS:
CALL STACK:
    DoesNotUnderstandError:reportError   06C43B10
        arg this = <instance of DoesNotUnderstandError>
    Nil:handleError   06C43AB0
        arg this = nil
        arg error = <instance of DoesNotUnderstandError>
    Thread:handleError   06C439F0
        arg this = <instance of Thread>
        arg error = <instance of DoesNotUnderstandError>
    Object:throw   06C43990
        arg this = <instance of DoesNotUnderstandError>
    Object:doesNotUnderstand   06C43930
        arg this = "which mate"
        arg selector = 'unixCmdGetStdOut'
        arg args = [_0]
    < FunctionDef in Method Meta_SC3Controller:initClass >   06C438D0
        var whichMate = nil
    Meta_SC3Controller:initClass   06C435D0
        arg this = class SC3Controller
    Meta_Class:initClassTree   06C43450
        arg this = class Class
        arg aClass = class SC3Controller
        var implementsInitClass = nil
    ArrayedCollection:do   068B5FE0
        arg this = [_437]
        arg function = <instance of Function>
        var i = 416
    Meta_Class:initClassTree   068B5DD0
        arg this = class Class
        arg aClass = class Object
        var implementsInitClass = nil
    Process:startup   068B5460
        arg this = <instance of Main>
        var time = 580.1903562
    Main:startup   068B53A0
        arg this = <instance of Main>
/quit sent

**Comment by sbl** [comment]
See my comment here: 
http://github.com/sbl/supercollider-tmbundle/commit/266352f8759abd902d26520aee934ec466fa0feb#comments
